name: Run Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_PASSWORD: ${{ secrets.SAUCE_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Install dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Install Node.js dependencies
        run: npm install  # This step installs your project's Node.js dependencies

      - name: Install Playwright browsers
        run: npx playwright install  # Now this will run after dependencies are installed

      - name: Run tests
        run: dotnet test --configuration Release --no-build --logger "console;verbosity=detailed"
